version: 2
jobs:
  build:
    working_directory: ~/TaskManagment
    docker:
      - image: circleci/node:12.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: angular-build
          command: npm build
      - run:
          name: angular-test
          command: npm test-cov
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                name: Publish package
                command: npm publish
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - persist_to_workspace:
          root: ~/repo
          paths: .



